# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-06 21:34
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Challenge',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='ChallengeStep',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('NOT_STARTED', 'Not started'), ('IN_PROGRESS', 'In progress'), ('DONE', 'Done'), ('ERROR', 'Error')], default='NOT_STARTED', max_length=11)),
                ('message', models.CharField(blank=True, max_length=140)),
            ],
        ),
        migrations.CreateModel(
            name='IdentityLeakCheckerChallenge',
            fields=[
                ('challenge_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='challenges.Challenge')),
            ],
            bases=('challenges.challenge',),
        ),
        migrations.CreateModel(
            name='TorChallenge',
            fields=[
                ('challenge_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='challenges.Challenge')),
            ],
            bases=('challenges.challenge',),
        ),
        migrations.AddField(
            model_name='challengestep',
            name='challenge',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='challenges.Challenge'),
        ),
        migrations.AddField(
            model_name='challenge',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
