# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-18 11:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='identityleakcheckerchallenge',
            name='check_email_status',
            field=models.CharField(choices=[('NOT_STARTED', 'Not started'), ('IN_PROGRESS', 'In progress'), ('COMPLETED', 'Completed'), ('ERROR', 'Error')], default='NOT_STARTED', max_length=11),
        ),
        migrations.AddField(
            model_name='torchallenge',
            name='check_tor_connection_status',
            field=models.CharField(choices=[('NOT_STARTED', 'Not started'), ('IN_PROGRESS', 'In progress'), ('COMPLETED', 'Completed'), ('ERROR', 'Error')], default='NOT_STARTED', max_length=11),
        ),
    ]
